#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = Same
PROCESS         = PROCESS.GOC
UI              = MAIN.GOC DIALOG.goh
UI_TO_RDFS      =
OBJS            = PROCESS.obj MAIN.obj
COMMON          = SAME.GOH
MODULES         =
CMODULES        = PROCESS UI
SRCS            = $(PROCESS) $(UI) $(COMMON)
LOBJS           =

PRODUCTS        = desktop nokia 

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
